# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  # Se déclenche lors des pushs sur la branche par défaut
  push:
    branches: ["main"]

  # Vous permet d'exécuter ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14 # Vous pouvez spécifier la version de Node souhaitée
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
